# Generated by Django 4.1.1 on 2023-07-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('V', 'Vendedor'), ('G', 'Gerente')], max_length=1),
        ),
    ]
